#App configuration values
[base]
start-block = 16323001 # start indexing at beginning of the blockchain, -1 to resume from highest block indexed
end-block = 16323003 # stop indexing at this block, -1 to never stop indexing
reindex = false # if true, this will re-attempt to index blocks we have already indexed (defaults to false)
prevent-reattempts = false # if true, this will prevent us from re-attempting to index failed blocks (defaults to false)
throttling = 0.2
index-chain = true #If false, we won't attempt to index the chain
exit-when-caught-up = false #mainly used for Osmosis rewards indexing
index-block-events = false #index block events for the particular chain
index-epoch-events = false
dry = false # if true, indexing will occur but data will not be written to the database.
api = "http://51.89.194.238:1317" # node api endpoint
rpc-workers = 1

#Lens config options
[lens]
rpc = "http://51.89.194.238:26657"
account-prefix = "ki"
chain-id = "kichain-2"
chain-name = "kid"

#postgresql
[database]
host = "localhost"
port = "5432"
database = "postgres"
user = "taxuser"
password = "password"
log-level = "error"c