#App configuration values
[base]
start-block = 10647117 # start indexing at beginning of the blockchain, -1 to resume from highest block indexed
end-block = 10647451 # stop indexing at this block, -1 to never stop indexing
reindex = true # if true, this will re-attempt to index blocks we have already indexed (defaults to false)
prevent-reattempts = false # if true, this will prevent us from re-attempting to index failed blocks (defaults to false)
throttling = 0.1
index-chain = true #If false, we won't attempt to index the chain
exit-when-caught-up = true #mainly used for Osmosis rewards indexing
index-block-events = false #index block events for the particular chain
index-epoch-events = false
dry = false # if true, indexing will occur but data will not be written to the database.
api = "https://api-challenge.blockchain.ki" # node api endpoint
rpc-workers = 1

#Lens config options
[lens]
rpc = "https://rpc-challenge.blockchain.ki"
account-prefix = "tki"
chain-id = "kichain-t-4"
chain-name = "kid"

#postgresql
[database]
host = "localhost"
port = "5432"
database = "postgres"
user = "taxuser"
password = "password"
log-level = "error"